export const SERVICES = [
  {
    name: 'restreamio',
    icon: 'https://restream.io/favicon.ico',
    url: 'https://restream.io/',
    label: 'Restream.io',
    pushBy: null,
    supportedByRestreamIo: false,
  },
  {
    name: 'twitch',
    icon: 'https://www.twitch.tv/favicon.ico',
    url: 'https://www.twitch.tv/',
    label: 'Twitch',
    pushBy: null,
    supportedByRestreamIo: true,
  },
  {
    name: 'peercaststation',
    // tslint:disable-next-line:no-http-string
    icon: 'http://127.0.0.1:7144/html/favicon.ico',
    // tslint:disable-next-line:no-http-string
    url: 'http://www.pecastation.org/',
    label: 'PeerCastStation',
    pushBy: 'nginx',
    supportedByRestreamIo: false,
  },
  {
    name: 'youtube',
    icon: 'https://s.ytimg.com/yts/img/favicon_32-vfl8NGn4k.png',
    url: 'https://www.youtube.com/',
    label: 'YouTube',
    pushBy: 'ffmpeg',
    supportedByRestreamIo: true,
  },
  {
    name: 'fresh',
    icon: 'https://freshlive.tv/assets/1479961350/favicon.ico',
    url: 'https://freshlive.tv/',
    label: 'FRESH!',
    pushBy: null,
    supportedByRestreamIo: false,
  },
  {
    name: 'cavetube',
    icon: 'https://www.cavelis.net/favicon.ico',
    url: 'https://www.cavelis.net/',
    label: 'CaveTube',
    pushBy: 'ffmpeg',
    supportedByRestreamIo: true,
  },
  {
    name: 'livecodingtv',
    icon: 'https://www.livecoding.tv/favicon.ico',
    url: 'https://www.livecoding.tv/',
    label: 'Livecoding.tv',
    pushBy: null,
    supportedByRestreamIo: true,
  },
  {
    name: 'niconico',
    icon: 'https://www.nicovideo.jp/favicon.ico',
    url: 'https://live.nicovideo.jp/',
    label: 'niconico',
    pushBy: null,
    supportedByRestreamIo: true,
  },
  {
    name: 'other1',
    icon: '',
    url: '',
    label: 'Other 1',
    pushBy: null,
    supportedByRestreamIo: false,
  },
  {
    name: 'other2',
    icon: '',
    url: '',
    label: 'Other 2',
    pushBy: null,
    supportedByRestreamIo: false,
  },
  {
    name: 'other3',
    icon: '',
    url: '',
    label: 'Other 3',
    pushBy: null,
    supportedByRestreamIo: false,
  },
];
